icons = "awesome"

[theme]
name = "solarized-dark"
[theme.overrides]
# idle_bg = "#123456"
idle_fg = "#abcdef"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
interval = 60
unit = "GiB"
format = "{icon}{used}/{total}{unit} ({available}{unit} free)"

[[block]]
block = "nvidia_gpu"
label = "GTX 1080"
show_memory = true
show_clocks = false
show_temperature = true
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB/{MTg}GB"
format_swap = "{SUg}GB/{STg}GB"
clickable = true
interval = 5
warning_mem = 45
warning_swap = 45
critical_mem = 75
critical_swap = 75

[[block]]
block = "cpu"
# format = "{barchart} {utilization}% {frequency}GHz"
format = "{utilization}% {frequency}GHz"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "battery"
#driver = "upower"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %m-%d %R"

