call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
Plug 'davidhalter/jedi-vim', { 'for': ['py', 'vpy'] }
Plug 'ycm-core/YouCompleteMe', { 'do': './install.py --clang-completer',  'for': ['c', 'cpp'] }
Plug 'dracula/vim', { 'as': 'dracula' }
"Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }
"Plug 'ludovicchabant/vim-gutentags'
"Plug 'junegunn/fzf', { 'do': './install --all' }
"Plug 'junegunn/fzf.vim'
call plug#end()

colorscheme dracula

" no clear screen when exit vim
set tabstop=4
set backspace=indent,eol,start
set encoding=utf-8

highlight Lf_hl_rgHighlight guifg=#000000 guibg=#CCCC66 ctermfg=green ctermbg=185
highlight Lf_hl_match gui=bold guifg=Blue cterm=bold ctermfg=green
highlight Lf_hl_match0 gui=bold guifg=Blue cterm=bold ctermfg=green
highlight Lf_hl_match1 gui=bold guifg=Blue cterm=bold ctermfg=green
highlight Lf_hl_match2 gui=bold guifg=Blue cterm=bold ctermfg=green
highlight Lf_hl_match3 gui=bold guifg=Blue cterm=bold ctermfg=green
highlight Lf_hl_match4 gui=bold guifg=Blue cterm=bold ctermfg=green
highlight Lf_hl_matchRefine  gui=bold guifg=Magenta cterm=bold ctermfg=green

"let g:jedi#completions_command = "<C-g>"
let g:ycm_global_ycm_extra_conf='~/.vim/plugged/YouCompleteMe/third_party/ycmd/.ycm_extra_conf.py'
